services:

  db:
    image: postgres:17.6
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_DB: resenha
      POSTGRES_PASSWORD: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - db:/var/lib/postgresql/data

  adminer:
    image: adminer:5.4.0
    restart: always
    ports:
      - 127.0.0.1:8585:8080

volumes:
  db: